### PR TITLE
build: switch to rollup for bundling

### PR DESCRIPTION
**Pull request by DSchau**
Luis -

First of all, love the utility; thank you so much!

Many "libraries", utilities, etc. (most notably React) have begun to switch to Rollup for bundling their assets into a small, neat module that can be easily consumed by other dependents.

This PR simply adds in Rollup support, and bundles as a UMD build. Practically, there won't be a difference in the output (yet... !) because you were already distributing as a UMD, but this does allow us to modularize the code base, and have utilities (e.g. the async forEach) externalized and not contained within a single monolithic file.

Let me know if there's anything else I can explain, or help figure out!

Note, [this article](https://medium.com/webpack/webpack-and-rollup-the-same-but-different-a41ad427058c) (by the author of Rollup) may be interesting to you.

Thanks!

### CODE REVIEW

**Comment by DSchau** [comment]
@luisvinicius167 any interest in getting this merged in? Thanks!

**Comment by luisvinicius167** [comment]
@DSchau my apologizes for long response time! Your do an awesome work, thanks!

**Comment by DSchau** [comment]
Awesome news @luisvinicius167; thanks so much! I may do a PR this weekend with some of those changes/improvements (e.g. modularizing the code base) I was referring to earlier. Have a great day!

**Comment by luisvinicius167** [comment]
@DSchau Great!

**Pull request merged**
